In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as ply
import seaborn as sns

In [2]:
data=pd.read_csv('C:/mydata/application_record.csv')
d1=pd.DataFrame(data)

In [3]:
d1.head

<bound method NDFrame.head of              ID CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  \
0       5008804           M            Y               Y             0   
1       5008805           M            Y               Y             0   
2       5008806           M            Y               Y             0   
3       5008808           F            N               Y             0   
4       5008809           F            N               Y             0   
...         ...         ...          ...             ...           ...   
438552  6840104           M            N               Y             0   
438553  6840222           F            N               N             0   
438554  6841878           F            N               N             0   
438555  6842765           F            N               Y             0   
438556  6842885           F            N               Y             0   

        AMT_INCOME_TOTAL      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE  \


In [4]:
d1.columns

Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS'],
      dtype='object')

In [5]:
d1.isnull().sum()

ID                          0
CODE_GENDER                 0
FLAG_OWN_CAR                0
FLAG_OWN_REALTY             0
CNT_CHILDREN                0
AMT_INCOME_TOTAL            0
NAME_INCOME_TYPE            0
NAME_EDUCATION_TYPE         0
NAME_FAMILY_STATUS          0
NAME_HOUSING_TYPE           0
DAYS_BIRTH                  0
DAYS_EMPLOYED               0
FLAG_MOBIL                  0
FLAG_WORK_PHONE             0
FLAG_PHONE                  0
FLAG_EMAIL                  0
OCCUPATION_TYPE        134203
CNT_FAM_MEMBERS             0
dtype: int64

In [6]:
d1.drop('OCCUPATION_TYPE', axis=1)

ID CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  \
0       5008804           M            Y               Y             0   
1       5008805           M            Y               Y             0   
2       5008806           M            Y               Y             0   
3       5008808           F            N               Y             0   
4       5008809           F            N               Y             0   
...         ...         ...          ...             ...           ...   
438552  6840104           M            N               Y             0   
438553  6840222           F            N               N             0   
438554  6841878           F            N               N             0   
438555  6842765           F            N               Y             0   
438556  6842885           F            N               Y             0   

        AMT_INCOME_TOTAL      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE  \
0               427500.0               Working               Higher education   
1               427500.0               Working               Higher education   
2               112500.0               Working  Secondary / secondary special   
3               270000.0  Commercial associate  Secondary / secondary special   
4               270000.0  Commercial associate  Secondary / secondary special   
...                  ...                   ...                            ...   
438552          135000.0             Pensioner  Secondary / secondary special   
438553          103500.0               Working  Secondary / secondary special   
438554           54000.0  Commercial associate               Higher education   
438555           72000.0             Pensioner  Secondary / secondary special   
438556          121500.0               Working  Secondary / secondary special   

          NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
0             Civil marriage   Rented apartment      -12005          -4542   
1             Civil marriage   Rented apartment      -12005          -4542   
2                    Married  House / apartment      -21474          -1134   
3       Single / not married  House / apartment      -19110          -3051   
4       Single / not married  House / apartment      -19110          -3051   
...                      ...                ...         ...            ...   
438552             Separated  House / apartment      -22717         365243   
438553  Single / not married  House / apartment      -15939          -3007   
438554  Single / not married       With parents       -8169           -372   
438555               Married  House / apartment      -21673         365243   
438556               Married  House / apartment      -18858          -1201   

        FLAG_MOBIL  FLAG_WORK_PHONE  FLAG_PHONE  FLAG_EMAIL  CNT_FAM_MEMBERS  
0                1                1           0           0              2.0  
1                1                1           0           0              2.0  
2                1                0           0           0              2.0  
3                1                0           1           1              1.0  
4                1                0           1           1              1.0  
...            ...              ...         ...         ...              ...  
438552           1                0           0           0              1.0  
438553           1                0           0           0              1.0  
438554           1                1           0           0              1.0  
438555           1                0           0           0              2.0  
438556           1                0           1           0              2.0  

[438557 rows x 17 columns]

In [7]:
d1.dtypes

ID                       int64
CODE_GENDER             object
FLAG_OWN_CAR            object
FLAG_OWN_REALTY         object
CNT_CHILDREN             int64
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE        object
NAME_EDUCATION_TYPE     object
NAME_FAMILY_STATUS      object
NAME_HOUSING_TYPE       object
DAYS_BIRTH               int64
DAYS_EMPLOYED            int64
FLAG_MOBIL               int64
FLAG_WORK_PHONE          int64
FLAG_PHONE               int64
FLAG_EMAIL               int64
OCCUPATION_TYPE         object
CNT_FAM_MEMBERS        float64
dtype: object

In [8]:
#Verileri dönüştürme

In [9]:
num= ['ID', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE', 'FLAG_EMAIL', 'CNT_FAM_MEMBERS']


In [10]:
for col in num:
    d1[col]=pd.to_numeric(d1[col], errors='coerce')

In [11]:
ktg = ['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE']

In [12]:
ktg = d1.select_dtypes(include=['category', 'object']).columns

In [13]:
d1.dtypes

ID                       int64
CODE_GENDER             object
FLAG_OWN_CAR            object
FLAG_OWN_REALTY         object
CNT_CHILDREN             int64
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE        object
NAME_EDUCATION_TYPE     object
NAME_FAMILY_STATUS      object
NAME_HOUSING_TYPE       object
DAYS_BIRTH               int64
DAYS_EMPLOYED            int64
FLAG_MOBIL               int64
FLAG_WORK_PHONE          int64
FLAG_PHONE               int64
FLAG_EMAIL               int64
OCCUPATION_TYPE         object
CNT_FAM_MEMBERS        float64
dtype: object

In [14]:
#Verileri dönüştürme
from sklearn.preprocessing import LabelEncoder


In [15]:
label_encoders={}
for stn in ktg:
    le=LabelEncoder()
    d1[stn]=le.fit_transform(d1[stn])
    label_encoders[stn]=le


In [16]:
print(d1.dtypes)

ID                       int64
CODE_GENDER              int32
FLAG_OWN_CAR             int32
FLAG_OWN_REALTY          int32
CNT_CHILDREN             int64
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE         int32
NAME_EDUCATION_TYPE      int32
NAME_FAMILY_STATUS       int32
NAME_HOUSING_TYPE        int32
DAYS_BIRTH               int64
DAYS_EMPLOYED            int64
FLAG_MOBIL               int64
FLAG_WORK_PHONE          int64
FLAG_PHONE               int64
FLAG_EMAIL               int64
OCCUPATION_TYPE          int32
CNT_FAM_MEMBERS        float64
dtype: object


In [17]:
#2. veri setini yükleme

In [18]:
d2=pd.read_csv('C:/mydata/credit_record.csv')

In [19]:
d2.head

<bound method NDFrame.head of               ID  MONTHS_BALANCE STATUS
0        5001711               0      X
1        5001711              -1      0
2        5001711              -2      0
3        5001711              -3      0
4        5001712               0      C
...          ...             ...    ...
1048570  5150487             -25      C
1048571  5150487             -26      C
1048572  5150487             -27      C
1048573  5150487             -28      C
1048574  5150487             -29      C

[1048575 rows x 3 columns]>

In [20]:
d2.dtypes

ID                 int64
MONTHS_BALANCE     int64
STATUS            object
dtype: object

In [21]:
#Veri dönüştürme

In [22]:
le=LabelEncoder()

In [23]:
d2['STATUS'] =le.fit_transform(d2['STATUS'])


In [24]:
d2.dtypes

ID                int64
MONTHS_BALANCE    int64
STATUS            int32
dtype: object

In [25]:
d2.isnull().sum()

ID                0
MONTHS_BALANCE    0
STATUS            0
dtype: int64

In [26]:
#İki veri setini birleştirme

In [27]:
d3=pd.concat([d1,d2])

In [28]:
d3.dtypes

ID                       int64
CODE_GENDER            float64
FLAG_OWN_CAR           float64
FLAG_OWN_REALTY        float64
CNT_CHILDREN           float64
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE       float64
NAME_EDUCATION_TYPE    float64
NAME_FAMILY_STATUS     float64
NAME_HOUSING_TYPE      float64
DAYS_BIRTH             float64
DAYS_EMPLOYED          float64
FLAG_MOBIL             float64
FLAG_WORK_PHONE        float64
FLAG_PHONE             float64
FLAG_EMAIL             float64
OCCUPATION_TYPE        float64
CNT_FAM_MEMBERS        float64
MONTHS_BALANCE         float64
STATUS                 float64
dtype: object

In [29]:
d3.columns

Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'MONTHS_BALANCE',
       'STATUS'],
      dtype='object')

In [30]:
d3 = pd.merge(d1, d2, on='ID', how='inner')

In [31]:
d3.head()

ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
0  5008804            1             1                1             0   
1  5008804            1             1                1             0   
2  5008804            1             1                1             0   
3  5008804            1             1                1             0   
4  5008804            1             1                1             0   

   AMT_INCOME_TOTAL  NAME_INCOME_TYPE  NAME_EDUCATION_TYPE  \
0          427500.0                 4                    1   
1          427500.0                 4                    1   
2          427500.0                 4                    1   
3          427500.0                 4                    1   
4          427500.0                 4                    1   

   NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
0                   0                  4      -12005          -4542   
1                   0                  4      -12005          -4542   
2                   0                  4      -12005          -4542   
3                   0                  4      -12005          -4542   
4                   0                  4      -12005          -4542   

   FLAG_MOBIL  FLAG_WORK_PHONE  FLAG_PHONE  FLAG_EMAIL  OCCUPATION_TYPE  \
0           1                1           0           0               18   
1           1                1           0           0               18   
2           1                1           0           0               18   
3           1                1           0           0               18   
4           1                1           0           0               18   

   CNT_FAM_MEMBERS  MONTHS_BALANCE  STATUS  
0              2.0               0       6  
1              2.0              -1       6  
2              2.0              -2       6  
3              2.0              -3       6  
4              2.0              -4       6

In [32]:
d3.dtypes

ID                       int64
CODE_GENDER              int32
FLAG_OWN_CAR             int32
FLAG_OWN_REALTY          int32
CNT_CHILDREN             int64
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE         int32
NAME_EDUCATION_TYPE      int32
NAME_FAMILY_STATUS       int32
NAME_HOUSING_TYPE        int32
DAYS_BIRTH               int64
DAYS_EMPLOYED            int64
FLAG_MOBIL               int64
FLAG_WORK_PHONE          int64
FLAG_PHONE               int64
FLAG_EMAIL               int64
OCCUPATION_TYPE          int32
CNT_FAM_MEMBERS        float64
MONTHS_BALANCE           int64
STATUS                   int32
dtype: object

In [33]:
d3.isnull().sum()

ID                     0
CODE_GENDER            0
FLAG_OWN_CAR           0
FLAG_OWN_REALTY        0
CNT_CHILDREN           0
AMT_INCOME_TOTAL       0
NAME_INCOME_TYPE       0
NAME_EDUCATION_TYPE    0
NAME_FAMILY_STATUS     0
NAME_HOUSING_TYPE      0
DAYS_BIRTH             0
DAYS_EMPLOYED          0
FLAG_MOBIL             0
FLAG_WORK_PHONE        0
FLAG_PHONE             0
FLAG_EMAIL             0
OCCUPATION_TYPE        0
CNT_FAM_MEMBERS        0
MONTHS_BALANCE         0
STATUS                 0
dtype: int64

In [34]:
#veri setine yeni özellikler ekleme

In [35]:
d3['AGE'] = d3['DAYS_BIRTH'] // -365
d3['YEARS_EMPLOYED'] = d3['DAYS_EMPLOYED'] // -365
d3.drop(['DAYS_BIRTH', 'DAYS_EMPLOYED'], axis=1, inplace=True)


In [36]:
#StandartScaler ile veriyi ölçeklendirme
from sklearn.preprocessing import StandardScaler


In [41]:
sc=StandardScaler()
scd_data=sc.fit_transform(d3)
scd_d3=pd.DataFrame(scd_data, columns=d3.columns)

In [42]:
print(scd_d3)

              ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
0      -1.673005     1.415747      1.247095         0.718448     -0.574026   
1      -1.673005     1.415747      1.247095         0.718448     -0.574026   
2      -1.673005     1.415747      1.247095         0.718448     -0.574026   
3      -1.673005     1.415747      1.247095         0.718448     -0.574026   
4      -1.673005     1.415747      1.247095         0.718448     -0.574026   
...          ...          ...           ...              ...           ...   
777710  1.712596     1.415747     -0.801863         0.718448     -0.574026   
777711  1.712596     1.415747     -0.801863         0.718448     -0.574026   
777712  1.712596     1.415747     -0.801863         0.718448     -0.574026   
777713  1.712596     1.415747     -0.801863         0.718448     -0.574026   
777714  1.712596     1.415747     -0.801863         0.718448     -0.574026   

        AMT_INCOME_TOTAL  NAME_INCOME_TYPE  NAME_EDUCATION_TYPE

In [43]:
d3.rename(columns={'STATUS': 'Status'}, inplace=True)

# Yeni isimle veri setini kontrol edin
print(d3.columns)



Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'FLAG_MOBIL',
       'FLAG_WORK_PHONE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE',
       'CNT_FAM_MEMBERS', 'MONTHS_BALANCE', 'Status', 'AGE', 'YEARS_EMPLOYED'],
      dtype='object')


In [44]:
#Eğitim ve Test
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [45]:
x = d3.loc[:, d3.columns != 'Status']
y = d3.loc[:, 'Status']


In [46]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [47]:
#Karar Ağaçları 
dcs=DecisionTreeClassifier(random_state=42)
dcs.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [48]:
y_pred=dcs.predict(x_test)

In [52]:
ac=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
cr=classification_report(y_test,y_pred)

In [53]:
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8697787750011251
              precision    recall  f1-score   support

           0       0.84      0.85      0.84     58131
           1       0.27      0.30      0.28      1749
           2       0.12      0.14      0.13       160
           3       0.12      0.14      0.13        57
           4       0.12      0.09      0.10        43
           5       0.83      0.83      0.83       306
           6       0.95      0.94      0.95     65907
           7       0.80      0.79      0.79     29190

    accuracy                           0.87    155543
   macro avg       0.51      0.51      0.51    155543
weighted avg       0.87      0.87      0.87    155543

[[49202  1078    52     6     5     9  2536  5243]
 [ 1016   523    46     3     0     1    87    73]
 [   33    67    22    18     2     3     4    11]
 [    4     3    28     8     8     1     3     2]
 [    3     0     4    23     4     8     0     1]
 [   17     2     1     3    13   253     7    10]
 [ 2930   171 